services:
  postgres:
    image: postgres:16
    container_name: zuno_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zuno_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zuno_app
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://969bbb461f3e27e05596f57fd3ec3e3df7a8069ed42763bd1a3a9882eebf8660:sk_N1HhSVJM91-7P3k_C-uh0@db.prisma.io:5432/postgres?sslmode=verify-full
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      # - DATABASE_URL=postgresql://admin:admin@postgres:5432/zuno_db?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # Command sequence: install -> generate -> push db schema -> seed -> dev
    command: >
      sh -c "
        bun install &&
        bun prisma generate &&
        bun prisma db push &&
        bun run seed &&
        bun run dev
      "

volumes:
  pgdata:
